.Dd 4/10/21
.Dt secret 1
.Os Ubuntu
.Sh NAME
.Nm secret
.Nm - File transfer via hidden channel 
.Sh SYNOPSIS
.Nm
-r [file|folder] -s [ip|hostname] {-l} {-h}
.br
 [] - requried options
.br
 {} - optional options
.Sh DESCRIPTION
.Nm 
is simple client / server program to send files secretly through ICMP packets. Communication is encrypted with AES encryption.
The server is able to receive files from multiple clients at same time. Support for ipv4 and ipv6 protocols.
.Pp 
.Pp 
A list of options and their descriptions:
.Bl -tag -width -indent
.It Fl r file|folder   
The name of the file to send or folder. Sends all files in folder and its subfolders.
.It Fl s ip|hostname
Ip address / hostname to which the file should be sent
.It Fl l
Start server and listen for ICMP packets.
.It Fl h
Print help
.El
.Pp 
[NOTE] option -l can be used without -r and -s options.
.br
[NOTE] this program requires root privileges to work correctly
.br
[NOTE] to stop server use Ctrl + C
.Pp
.Sh EXAMPLE USAGE
.Nm 
-r README.MD -s 127.0.0.1 
.br
.Nm 
-r movie.avi -s google.sk
.br
.br
.Nm 
-r folderName -s 127.0.0.1
.br
.Nm 
-l
.br
.Nm 
-h
.Sh FILES
.Bl -tag -width -compact
.It Pa ./Makefile
.It Pa ./manual.pdf
.It Pa ./secret.1
.It Pa ./src/main.cpp
.It Pa ./src/main.h
.It Pa ./src/icmp_client.cpp
.It Pa ./src/icmp_client.h
.It Pa ./src/icmp_server.cpp
.It Pa ./src/icmp_server.h
.It Pa ./src/help_functions.cpp
.It Pa ./src/help_functions.h
.El